# curl --location --request POST 'localhost:8080/ibu'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"TargetOriginalGravity": 1.063,
#	"BoilSize": 7.5,
#	"BatchSize": 6.0,
#	"Hops": [
#		{
#			"Name": "Centennial",
#			"Ounces": 2.5,
#			"AlphaAcids": 6.2,
#			"BoilTime": 45,
#			"Type": "Pellets"
#		},
#		{
#			"Name": "Cascade",
#			"Ounces": 4,
#			"AlphaAcids": 5.3,
#			"BoilTime": 15,
#			"Type": "Pellets"
#		}
#	]
#}'
POST localhost:8080/ibu
Content-Type: application/json

{
	"TargetOriginalGravity": 1.063,
	"BoilSize": 7.5,
	"BatchSize": 6.0,
	"Hops": [
		{
			"Name": "Centennial",
			"Ounces": 2.5,
			"AlphaAcids": 6.2,
			"BoilTime": 45,
			"Type": "Pellets"
		},
		{
			"Name": "Cascade",
			"Ounces": 4,
			"AlphaAcids": 5.3,
			"BoilTime": 15,
			"Type": "Pellets"
		}
	]
}

###

# curl --location --request GET 'localhost:8080/fermentables/id/299'
GET localhost:8080/fermentables/id/299

###

# curl --location --request GET 'localhost:8080/fermentables/rye'
GET localhost:8080/fermentables/rye

###

# curl --location --request GET 'localhost:8080/fermentables'
GET localhost:8080/fermentables

###

# curl --location --request POST 'localhost:8080/srm'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"GrainBill": [
#		{
#			"Name": "Special Roast",
#			"Amount": 1.5
#		},
#		{
#			"Name": "Caramel / Crystal 40L",
#			"Amount": 3.4
#		},
#		{
#			"Name": "Rye",
#			"Amount": 2.1
#		},
#		{
#			"Name": "American 2-Row",
#			"Amount": 6.3
#		}
#	],
#	"BatchSize": 7.0
#}'
POST localhost:8080/srm
Content-Type: application/json

{
	"GrainBill": [
		{
			"Name": "Special Roast",
			"Amount": 1.5
		},
		{
			"Name": "Caramel / Crystal 40L",
			"Amount": 3.4
		},
		{
			"Name": "Rye",
			"Amount": 2.1
		},
		{
			"Name": "American 2-Row",
			"Amount": 6.3
		}
	],
	"BatchSize": 7.0
}

###

# curl --location --request POST 'localhost:8080/hydrometer-adjustment'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"MeasuredGravity": 1.056,
#	"TemperatureReading": 54,
#	"CalibrationTemp": 68
#}'
POST localhost:8080/hydrometer-adjustment
Content-Type: application/json

{
	"MeasuredGravity": 1.056,
	"TemperatureReading": 54,
	"CalibrationTemp": 68
}

###

# curl --location --request POST 'localhost:8080/abv'
#--header 'Content-Type: application/json'
#--data-raw '{
#	"OriginalGravity": 1.056,
#	"FinalGravity": 1.012
#}'
POST localhost:8080/abv
Content-Type: application/json

{
	"OriginalGravity": 1.056,
	"FinalGravity": 1.012
}

###

